# Generated by Django 6.0.5 on 2026-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RunActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(
                        help_text="Garmin Activity ID", max_length=100, unique=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("distance_km", models.FloatField()),
                ("duration_minutes", models.FloatField()),
                (
                    "elevation_gain",
                    models.FloatField(
                        blank=True, help_text="Elevation gain in meters", null=True
                    ),
                ),
                (
                    "tss",
                    models.FloatField(
                        blank=True, help_text="Training Stress Score", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Run Activities",
                "ordering": ["-date"],
            },
        ),
    ]
