# Generated by Django 6.0.5 on 2026-06-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'London Marathon 2026'", max_length=200)),
                ('date', models.DateField()),
                ('goal_time', models.CharField(blank=True, help_text='Optional target time', max_length=20)),
                ('feeling', models.TextField(blank=True, help_text='Post-race reflection')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Auto-generated or custom name', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Typically the A race date')),
                ('a_race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_block', to='dashboard.arace')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Hackney Half'", max_length=200)),
                ('date', models.DateField()),
                ('distance_km', models.FloatField()),
                ('feeling', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('training_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_races', to='dashboard.trainingblock')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='runactivity',
            name='training_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='dashboard.trainingblock'),
        ),
        migrations.CreateModel(
            name='TrainingBlockSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Base', 'Race Specific', 'Taper'", max_length=100)),
                ('order', models.IntegerField(help_text='Sorting order: 0=Base, 1=Race Specific, 2=Taper')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('training_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dashboard.trainingblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
